Feature/referee
ericbrandwein/kamchatka pull request #27
Opened 2021-01-31 16:20 UTC by nsanmartin

Este pr esta medio incompleto porque depende de cambiar el conquer (basicamente separar el atacar del ocuppar una conquista, cosa qu ehace el refere, pero hay q sacar del combate pero sacarlo rompe 4 tests)  lo pospuse por tiempo. Además para agregar mas tests habria que usar un dado deterministico pero para eso tambien hay que codear (y leer) bastante y hoy es domingo (?

2021-01-31 17:38 UTC, ericbrandwein requested changes
Tenés ganas de que haga el iterator de players? O te gusta más así?

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/main/gamelogic/Referee.kt
> + *      2. occupier of from and to is the same and the currentPlayer
```suggestion
 * preconditions (checked in [validateRegroupings] method):
 *      1. `regroupings.distinctBy { it.from }.count() == regroupings.count()`
 *      2. occupier of from and to is the same as the currentPlayer
```
Sólo para tomar provecho de KDoc

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/main/gamelogic/Goal.kt
> +class Goal(val subGoals: List<SubGoal>) : SubGoal() {
las subGoals pueden ser una `Collection` en vez de una `List`? O necesitás los índices de los 
subGoals? Además, tienen que ser public?
```suggestion
class Goal(private val subGoals: Collection<SubGoal>) : SubGoal() {
```

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/main/gamelogic/Goal.kt
> +class Goal(val subGoals: List<SubGoal>) : SubGoal() {
Lo mismo con todos los otros parámetros del archivo, no pueden ser `private`?

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/test/RefereeTest.kt
> +    fun `Nico wins if he plays against eric (and achieve his goal first)`() {
```suggestion
    fun `Nico wins only if Eric lets him win because he feels sorry for him`() {
```

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/test/RefereeTest.kt
> +    fun `Nico wins if he plays against eric (and achieve his goal first)`() {
Ahora posta:
```suggestion
    fun `Nico wins if he plays against eric (and achieves his goal first)`() {
```

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/test/RefereeTest.kt
> +    fun `Turns change according list of playerInfo`() {
```suggestion
    fun `Turns change according to list of playerInfo`() {
```

Ya me conocés, soy hinchapelotas

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/main/gamelogic/Referee.kt
> +    public fun next(state:State) : State{
Claramente este método es algo que tiene que tener cada State. Por suerte los enums en Kotlin pueden tener métodos.

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/main/gamelogic/Referee.kt
> +        if (state == State.AddArmies) { changeTurn() }
Quizá el State debería tener un método que sea `shouldChangeTurn` o `isLastInTurn`? O que directamente el State tenga el `changeToNext`, que devuelve o cambia el próximo State y además llama a changeTurn() si es necesario. Cero ifs, Wilkinson estaría orgulloso.

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/main/gamelogic/Referee.kt
> +        if (n.toInt() > 3) { throw Exception("At most 3 armies can be regrouped") }
Para, podés pasar más de 3 ejéëcitos cuando estás reagrupando, podés pasar todos los que quieras. Lo de los 3 ejércitos es sólo cuando conquistás.

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/main/gamelogic/Referee.kt
> +            throw Exception("Cannot move ${n.toInt()} countries if they are not available in country")
```suggestion
            throw Exception("Cannot move ${n.toInt()} armies if they are not available in country")
```

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/main/gamelogic/Referee.kt
> +            throw Exception("countries must be bordering to regroup nut ${from} and ${to} are not")
```suggestion
            throw Exception("countries must be bordering to regroup but ${from} and ${to} are not")
```

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/main/gamelogic/Referee.kt
> +            throw Exception("Only one regroup per country per turn is allowed (to facilitate validation)")
jajajajajajaj re pajero. Esto grita por una clase aparte en la que puedas hacer reagrupes de a uno y se vaya guardando qué reagrupes podés hacer. Se puede agregar dsp igual.

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/main/gamelogic/Referee.kt
> +    fun regroup(regroupings: List<Regrouping>){
Uh me gustaría que el Referee fuese mucho más tonto y que delegue a otras clases para hacer propiamente el ataque y los reagrupes y etc.  Se puede cambiar después igual eso.

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/main/gamelogic/Referee.kt
> +           throw java.lang.Exception("Not th emoment to occypy conquered country")
```suggestion
           throw Exception("Not the moment to occupy conquered country")
```

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/main/gamelogic/Referee.kt
> +    fun regroup(regroupings: List<Regrouping>){
En realidad, se me ocurre que los States deberían ser los que manejen las acciones. Querés atacar? Perá que le pido a mi State que ataque. Ah, es el State.Regroup? Bueno, él se va a encargar de tirar una  excepción diciéndote que no podés.

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/main/gamelogic/Referee.kt
> +class Referee (val players:MutableList<PlayerInfo>, val politicalMap: PoliticalMap, val occupations: CountryOccupations){
En algún momento agregás o sacás cosas de la lista de players? Ah, es por si eliminás un player y se queda sin países?

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/main/gamelogic/Referee.kt
> +    var attackerCountry : Country? = null
Todas estas al ser public var puede venir alguien de afuera y cambiarlo como quiera. Feito

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/main/gamelogic/Referee.kt
> +    var player_index = 0
Se te chispoteó un snake case acá en vez de camel case. Creíste que no me iba a dar cuenta, eh? :angry:

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/main/gamelogic/Referee.kt
> +class CountryReinforcement(val country:Country, val n: PositiveInt) {
:scream: una variable de una sola letra. Eso no lo podemos permitir!
```suggestion
class CountryReinforcement(val country:Country, val armies: PositiveInt) {
```

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/main/gamelogic/Referee.kt
> +class CountryReinforcement(val country:Country, val n: PositiveInt) {
Che, ahora que veo estas clases así hechas que hacen cada comando tipo de country reinforcement y de Regrouping y esas cosas, me hace acordar creo que se llama al Command pattern que cada acción del usuario es un command, y entonces tenés una lista de Commands que le llamás apply a cada una y el referee como que se convierte solo en un llamador de Commands. Esto te deja después guardar fácil los commands que ocurrieron en un juego para después podes ver una repe re fácil, o también deshacer una acción que realizaste y te equivocaste, como por ejemplo reagrupar algo que no querías. Quizá sería copado hacer eso

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/main/gamelogic/Referee.kt
> +            throw java.lang.Exception("Player ${player} cannot add army to country")
Hace falta el package acá? Creo que se da cuenta java solo
```suggestion
            throw Exception("Player ${player} cannot add army to country")
```

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/main/gamelogic/Referee.kt
> +        if (state != State.Attack) { throw Exception("Cannot attack when not attacking state") }
```suggestion
        if (state != State.Attack) { throw Exception("Cannot attack when not in attacking state") }
```

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/main/gamelogic/Referee.kt
> +        else if (attackState != AttackState.Fight) { throw java.lang.Exception("Cannot attack if not fighting") }
```suggestion
        else if (attackState != AttackState.Fight) { throw Exception("Cannot attack if not fighting") }
```

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/main/gamelogic/Referee.kt
> +        val attacker = Attacker(occupations, combatResolver)
Creo que acá necesitamos un factory method que nos cree un `Attacker` con un `DiceRollingCombatResolver`, en vez de tener que crear 5000 objetos acá nomás

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/main/gamelogic/Referee.kt
> +            throw java.lang.Exception("player must occupy both countries to regroup")
```suggestion
            throw Exception("player must occupy both countries to regroup")
```

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/test/RefereeTest.kt
> +    fun `AddArmies add armies and change referee's state`() {
```suggestion
    fun `AddArmies adds armies and changes referee's state`() {
```

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/test/RefereeTest.kt
> +        assertTrue (sampleReferee.state == Referee.State.Attack)
Mmmm creeeeo que me gustaría más que le preguntes al referee `isAttacking` en vez de preguntarle el `State`. Además así lo podés hacer `private` al `State` y no lo pueden cambiar de afuera. Eso igual se puede resolver en Kotlin poniendo un `private set()`, pero igual me parece feo que le pidan el state al referee. Subjetivo igual

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/test/RefereeTest.kt
> +        assertTrue (sampleReferee.occupations.armiesOf(arg) == armiesBefore.plus(armiesToAdd))
Ufa, lo mismo acá, si pueden acceder a las occupations desde afuera cualquiera te las puede cambiar.

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/test/RefereeTest.kt
> +        assertTrue (sampleReferee.occupations.armiesOf(arg) == armiesBefore.plus(armiesToAdd))
el `.plus` em Kotlin, como es un `operator`, lo podés usar directamente como `+` si querés.

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/test/RefereeTest.kt
> +    fun `Regroup move the armies and change turn`() {
```suggestion
    fun `Regroup moves the armies and changes turn`() {
```

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/main/gamelogic/Referee.kt
> +    fun currentPlayer(): Player {  return players[player_index % players.size].name }
Una boludez, pero esto, `gameIsOver` y `winners` pueden ser [properties](https://kotlinlang.org/docs/reference/properties.html). Es cuestión de gustos igual

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/test/RefereeTest.kt
> +    fun `EndAttack ends the atack`() {
```suggestion
    fun `EndAttack ends the attack`() {
```

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/test/RefereeTest.kt
> +        assertTrue (referee.currentPlayer() == eric)
Uh, si tengo el referee puedo saber el goal del current player. Igual no creo que importe.

2021-01-31 17:38 UTC, ericbrandwein commented on core/src/main/gamelogic/PlayerInfo.kt
> +enum class Color{White, Black, Red, Blue, Green, Yellow, Brown, Gray}
Lo malo de usar `Color` de nombre es que `Color` ya existe en libgdx. Es más, hasta podríamos quizá usar la clase `Color` de libgdx para definir el color de un `Player`? Nah, estaríamos haciendo que el Referee dependa de libgdx.

2021-01-31 19:49 UTC, nsanmartin commented on core/src/main/gamelogic/Goal.kt
> +class Goal(val subGoals: List<SubGoal>) : SubGoal() {
Un año de python me mal acostrumbró. Es peor de lo que parece.

2021-01-31 19:54 UTC, nsanmartin commented on core/src/main/gamelogic/Referee.kt
> +        if (n.toInt() > 3) { throw Exception("At most 3 armies can be regrouped") }
Cierto

2021-01-31 20:03 UTC, nsanmartin commented on core/src/main/gamelogic/Referee.kt
> +    fun currentPlayer(): Player {  return players[player_index % players.size].name }
sep

2021-01-31 20:04 UTC, nsanmartin commented on core/src/main/gamelogic/Referee.kt
> +    public fun next(state:State) : State{
Uh, que bien.

2021-01-31 20:19 UTC, nsanmartin commented on core/src/main/gamelogic/Referee.kt
> +        if (state == State.AddArmies) { changeTurn() }
Lo que no me gusta de eso es que pasa a haber un "efecto secundario implicito" que es como una especie de goto para mi. Peor bueno, todo sea para que no tengas q ver ifs

2021-01-31 20:19 UTC, nsanmartin commented on core/src/main/gamelogic/Referee.kt
> +            throw Exception("Only one regroup per country per turn is allowed (to facilitate validation)")
Asi es.

2021-01-31 20:26 UTC, nsanmartin commented on core/src/main/gamelogic/Referee.kt
> +    fun regroup(regroupings: List<Regrouping>){
Para eso lo states tendrian que ser clases y no enums, o sea mas tiempo. Para mi este pr tenía suficientes líneas. Igual algo de eso hice, las clases CountryReinforcement y Regrouping hacen las acciones y lo chequeos. Pasa que algunos chequeos tienen que conocer el conjunto de las accione sa aplicar (todas las reagrupaciones ponele) y me pareció overkill hacer ademas un aclase para las agrupacione sde acciones y puse esos chequeos en referí porque "menos es más" (?

2021-01-31 20:30 UTC, nsanmartin commented on core/src/main/gamelogic/Referee.kt
> +class Referee (val players:MutableList<PlayerInfo>, val politicalMap: PoliticalMap, val occupations: CountryOccupations){
Cuando un jugador pierde (se queda sin ejércitos) lo elimino de la lista. Esto es basicamente para no tener que acordarme que esto pasó y entonces en el chequeo de gameOver no tengo que estar fijandome si fue que se lo acaba de eliminar en este turno o pasó antes.

2021-01-31 20:30 UTC, nsanmartin commented on core/src/main/gamelogic/Referee.kt
> +    var attackerCountry : Country? = null
Verdad (tengo una excusa: un año de python)

2021-01-31 20:37 UTC, nsanmartin commented on core/src/main/gamelogic/Referee.kt
> +    var player_index = 0
Fue sin querer

2021-01-31 20:43 UTC, nsanmartin commented on core/src/test/RefereeTest.kt
> +        assertTrue (referee.currentPlayer() == eric)
Uh, yo pensada que ibamos a poner un debuger en la pantalla mostrando todo el tiempo que habia en referee...

2021-01-31 20:44 UTC, nsanmartin commented on core/src/main/gamelogic/PlayerInfo.kt
> +enum class Color{White, Black, Red, Blue, Green, Yellow, Brown, Gray}
Si usar color de libgdx no me gusta. Para mí idealmente todo uso de libgdx deberís estar "encapsulado" en un solo "lugar"

2021-01-31 20:45 UTC, nsanmartin commented on core/src/main/gamelogic/Referee.kt
> +        val attacker = Attacker(occupations, combatResolver)
Otro día?

2021-01-31 20:47 UTC, nsanmartin commented on core/src/test/RefereeTest.kt
> +        assertTrue (sampleReferee.state == Referee.State.Attack)
Si el state ahora es private pero hay una property currentState (no se podiia llamar state) para que todos puedan saber en que estado estan.

2021-01-31 20:55 UTC, nsanmartin commented on core/src/test/RefereeTest.kt
> +        assertTrue (sampleReferee.occupations.armiesOf(arg) == armiesBefore.plus(armiesToAdd))
El tema es que si hacemos private las occupations, entonces Regrouping y Countryreinforcment no pueden hacer nada y todo eso va a ir a agrandar el referi. Y vos no querias un referi grande. Poenete de acuerdo (o usamos friend class o algo asi?)

2021-02-01 01:02 UTC, ericbrandwein requested changes
No te puedo responder a las que están outdated, pero [acá](https://github.com/ericbrandwein/kamchatka/pull/27#discussion_r567482900) tenés razón, extraño el package protected de java. Quizá la única solución es que tengas todas esas clases como internas de `Referee`. O que el Referee les pase las Occupations a esas otras clases en vez de pasarse a sí mismo.

2021-02-01 01:02 UTC, ericbrandwein commented on core/src/main/gamelogic/Referee.kt
> +    var gameIsOver : Boolean = false
No hace falta inicializar las properties estas si tienen un get(). Además pueden ser `val`.

2021-02-01 01:02 UTC, ericbrandwein commented on core/src/main/gamelogic/Referee.kt
> +    var winners : List<Player> = listOf()
Ahora que lo pienso, en ningún momento puede haber más de un winner. O lo hiciste lista así no usabas null?

2021-02-01 01:52 UTC, nsanmartin commented on core/src/main/gamelogic/Referee.kt
> +    var gameIsOver : Boolean = false
Ah el IDE me habia bardeado x no inicilizar. Creo que depende de si es var  o val.

2021-02-01 01:53 UTC, nsanmartin commented on core/src/main/gamelogic/Referee.kt
> +    var winners : List<Player> = listOf()
Si. La otra es usar maybe

2021-02-01 03:04 UTC, nsanmartin commented
https://github.com/ericbrandwein/kamchatka/pull/27#pullrequestreview-579956943
Empecé pasando occupation, después tuve q agregar politicalMap y me pareció que en realidad en vez de ir acumulando parámetros pasarlos ya agrupados como vienen en referee. Después de todo no es una biblioteca que otros vayan a usar pensé

2021-02-01 04:56 UTC, merged